# Generated by Django 4.2.7 on 2024-01-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('discription', models.CharField(blank=True, max_length=300)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('personce', models.IntegerField(default=0)),
            ],
        ),
    ]
