# Generated by Django 4.2.7 on 2024-01-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='date',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
