# Generated by Django 4.2.7 on 2024-01-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_package_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50)),
                ('destination', models.CharField(blank=True, max_length=300)),
                ('classe', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
