# Generated by Django 4.2.7 on 2024-01-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
