# Generated by Django 4.2.7 on 2024-01-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='hour_a',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='hour_d',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='ps1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='ps2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='classe',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
