# Generated by Django 4.2.7 on 2024-01-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_flight_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='checked_out',
            field=models.CharField(blank=True, default='no', max_length=10),
        ),
    ]
