# Generated by Django 4.2.7 on 2024-01-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_flight_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
