# Generated by Django 4.2.7 on 2024-02-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_flight_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='discription',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
