# Generated by Django 4.2.7 on 2024-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_package_country_alter_package_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
